version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=selfAwareDB
      - POSTGRES_USER=selfAware
      - POSTGRES_PASSWORD=selfAware

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
